### PR TITLE
Made the boot sequence more flexible

### PR DESCRIPTION
**Pull request by Lignum**
Hi, I recently saw your project on CCF. Great work on this, though I've got an addition to the boot sequence which will improve its speed and reliability.

### CODE REVIEW

**Comment by Lignum** [comment]
Cheers 🎊 

Hello @Lignumm you are an idiot some changes in this pull request have been reverted. -Zayne

**Comment by CrazedProgrammer** [comment]
Cheers

**Comment by demhydraz** [comment]
> Hello @Lignumm you are an idiot some changes in this pull request have been reverted. -Zayne
you do know this is not how you answer a comment right?

i think
you have
a mild
case of
retardation

**Comment by Lignum** [comment]
Obliviousness
Pull request
I have advice
Check the changes twice
Inculpable

**Pull request merged**
